repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.239
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/ggozad/gherkin-check
    rev: "v0.1.0" # Use the sha or tag you want to point at
    hooks:
      - id: gherkin-check
