name: Native Python Actions Workflow with Services

on:
  push:
  workflow_call:

permissions:
  checks: write
  pull-requests: write

jobs:
  setup-services:
    name: Setup Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Create directories for Selenoid
        run: |
          mkdir -p var/video
          mkdir -p var/log
          mkdir -p config/selenoid
          # Ensure permissions are correct
          chmod -R a+rwX var
          chmod -R a+rwX config

      - name: Upload directories as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: selenoid-directories
          path: |
            var/video
            var/log
            config/selenoid

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    name: Python ${{ matrix.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry" # Enable caching for Poetry dependencies

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Wait for Selenoid
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4444/status | grep -q '"ready":true'; then
              echo "Selenoid is ready!"
              break
            fi
            echo "Waiting for Selenoid to be ready..."
            sleep 2
          done

      - name: Check syntax
        run: poetry run flake8 .

      - name: Run Behave tests
        run: |
          poetry run behave --junit --junit-directory=reports tests/features

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "reports/TESTS-*.xml"

      - name: Publish Test Report
        if: always() # Always run even if the previous step fails
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: "**/TESTS-*.xml"
          comment: true

    services:
      # Selenoid service
      selenoid:
        image: aerokube/selenoid:latest
        ports:
          - 4444:4444
        options: >-
          --env OVERRIDE_VIDEO_OUTPUT_DIR=./var/video
          --mount type=bind,source=${{ github.workspace }}/var/video,target=/opt/selenoid/video
          --mount type=bind,source=${{ github.workspace }}/var/log,target=/opt/selenoid/logs
          --mount type=bind,source=${{ github.workspace }}/config/selenoid/browsers.json,target=/etc/selenoid/browsers.json

      # Selenoid UI service
      selenoid-ui:
        image: aerokube/selenoid-ui:latest
        ports:
          - 8082:8080
        options: >-
          --env SELENOID_URI=http://selenoid:4444

      # Firefox browser service
      firefox:
        image: selenoid/firefox:latest
        options: >-
          --entrypoint "echo Only here to make sure the image is available to selenoid"

      # Chrome browser service
      chrome:
        image: selenoid/chrome:latest
        options: >-
          --entrypoint "echo Only here to make sure the image is available to selenoid"
